In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings('ignore')

In [2]:
sales=pd.read_csv("~/Downloads/Bigmart.csv")

In [3]:
sales

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

# Feature engineering

In [4]:
sales['Item_ID_cat']=sales.Item_Identifier.str[0:2]

In [5]:
sales.Item_Fat_Content.replace(to_replace=['LF','low fat','reg'],
                              value=['Low Fat','Low Fat','Regular'],
                              inplace=True)

In [6]:
sales.loc[sales.Item_ID_cat=='NC','Item_Fat_Content'] = 'Non Edible'

In [7]:
pd.crosstab(sales.Item_ID_cat,sales.Item_Fat_Content)

Item_Fat_Content  Low Fat  Non Edible  Regular
Item_ID_cat
DR                    728           0       71
FD                   3190           0     2935
NC                      0        1599        0

In [8]:
sales.Item_Type.unique()

array(['Dairy', 'Soft Drinks', 'Meat', 'Fruits and Vegetables',
       'Household', 'Baking Goods', 'Snack Foods', 'Frozen Foods',
       'Breakfast', 'Health and Hygiene', 'Hard Drinks', 'Canned',
       'Breads', 'Starchy Foods', 'Others', 'Seafood'], dtype=object)

In [9]:
perish=['Dairy', 'Meat', 'Fruits and Vegetables','Breakfast','Breads', 'Starchy Foods', 'Seafood']

In [10]:
def funct(x):
    if x in perish:
        return('perishable')
    else:
        return('non_perishable')

In [11]:
sales['Item_cat']=sales.Item_Type.apply(funct)

In [12]:
sales.Outlet_Identifier.unique()

array(['OUT049', 'OUT018', 'OUT010', 'OUT013', 'OUT027', 'OUT045',
       'OUT017', 'OUT046', 'OUT035', 'OUT019'], dtype=object)

In [13]:
lowes=['OUT010', 'OUT019']
high=['OUT027', 'OUT013']

In [14]:
def outlets(x):
    if x in lowes:
        return('Low_performers')
    elif x in high:
        return('High_performers')
    else:
        return('Avg_performers')

In [15]:
sales['Outlet_cat']=sales.Outlet_Identifier.apply(outlets)

In [16]:
sales['Vintage']=2013-sales.Outlet_Establishment_Year

In [17]:
sales

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Item_ID_cat,Item_cat,Outlet_cat,Vintage
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,FD,perishable,Avg_performers,14
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,DR,non_perishable,Avg_performers,4
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,FD,perishable,Avg_performers,14
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,FD,perishable,Low_performers,15
4,NCD19,8.930,Non Edible,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,NC,non_perishable,High_performers,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,FD,non_perishable,High_performers,26
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850,FD,non_perishable,Avg_performers,11
8520,NCJ29,10.600,Non Edible,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,NC,non_perishable,Avg_performers,9
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,FD,non_perishable,Avg_performers,4
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,DR,non_perishable,Avg_performers,16

# Missing Values

In [18]:
sales.loc[sales.Item_Identifier=='FDA15']

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Item_ID_cat,Item_cat,Outlet_cat,Vintage
0,FDA15,9.3,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,FD,perishable,Avg_performers,14
831,FDA15,9.3,Low Fat,0.016055,Dairy,250.2092,OUT045,2002,NaN,Tier 2,Supermarket Type1,5976.2208,FD,perishable,Avg_performers,11
2599,FDA15,9.3,Low Fat,0.016019,Dairy,248.5092,OUT035,2004,Small,Tier 2,Supermarket Type1,6474.2392,FD,perishable,Avg_performers,9
2643,FDA15,9.3,Low Fat,0.016088,Dairy,249.6092,OUT018,2009,Medium,Tier 3,Supermarket Type2,5976.2208,FD,perishable,Avg_performers,4
4874,FDA15,9.3,Low Fat,0.026818,Dairy,248.9092,OUT010,1998,NaN,Tier 3,Grocery Store,498.0184,FD,perishable,Low_performers,15
5413,FDA15,9.3,Low Fat,0.016009,Dairy,250.6092,OUT013,1987,High,Tier 3,Supermarket Type1,6474.2392,FD,perishable,High_performers,26
6696,FDA15,NaN,Low Fat,0.015945,Dairy,249.5092,OUT027,1985,Medium,Tier 3,Supermarket Type3,6474.2392,FD,perishable,High_performers,28
7543,FDA15,9.3,Low Fat,0.016113,Dairy,248.8092,OUT017,2007,NaN,Tier 2,Supermarket Type1,5976.2208,FD,perishable,Avg_performers,6

In [19]:
sales['Item_Weight']=sales.groupby('Item_Identifier')['Item_Weight'].transform(lambda x:x.fillna(x.mean()))

In [20]:
sales.loc[sales.Item_Weight.isnull()]

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Item_ID_cat,Item_cat,Outlet_cat,Vintage
927,FDN52,NaN,Regular,0.130933,Frozen Foods,86.9198,OUT027,1985,Medium,Tier 3,Supermarket Type3,1569.9564,FD,non_perishable,High_performers,28
1922,FDK57,NaN,Low Fat,0.079904,Snack Foods,120.0440,OUT027,1985,Medium,Tier 3,Supermarket Type3,4434.2280,FD,non_perishable,High_performers,28
4187,FDE52,NaN,Regular,0.029742,Dairy,88.9514,OUT027,1985,Medium,Tier 3,Supermarket Type3,3453.5046,FD,perishable,High_performers,28
5022,FDQ60,NaN,Regular,0.191501,Baking Goods,121.2098,OUT019,1985,Small,Tier 1,Grocery Store,120.5098,FD,non_perishable,Low_performers,28

In [21]:
sales.loc[sales.Item_Type=='Frozen Foods','Item_Weight'].mean()

12.782403508771965

In [22]:
sales.loc[(sales.Item_Type=='Frozen Foods') & (sales.Item_Weight.isnull()),'Item_Weight'] = 12.782

In [23]:
sales.loc[sales.Item_Type=='Snack Foods','Item_Weight'].mean()

13.031230191826587

In [24]:
sales.loc[(sales.Item_Type=='Snack Foods') & (sales.Item_Weight.isnull()),'Item_Weight'] = 13.031

In [25]:
sales.loc[sales.Item_Type=='Dairy','Item_Weight'].mean()

13.37990455212926

In [26]:
sales.loc[(sales.Item_Type=='Dairy') & (sales.Item_Weight.isnull()),'Item_Weight'] = 13.379

In [27]:
sales.loc[sales.Item_Type=='Baking Goods','Item_Weight'].mean()

12.28531684698612

In [28]:
sales.loc[(sales.Item_Type=='Baking Goods') & (sales.Item_Weight.isnull()),'Item_Weight'] = 12.285

In [29]:
sales.groupby(['Outlet_Type','Outlet_Location_Type'])['Outlet_Size'].value_counts()

Outlet_Type        Outlet_Location_Type  Outlet_Size
Grocery Store      Tier 1                Small          528
Supermarket Type1  Tier 1                Medium         930
                                         Small          930
                   Tier 2                Small          930
                   Tier 3                High           932
Supermarket Type2  Tier 3                Medium         928
Supermarket Type3  Tier 3                Medium         935
Name: Outlet_Size, dtype: int64

In [30]:
sales.loc[sales.Outlet_Size.isnull(), ['Outlet_Location_Type','Outlet_Type']].value_counts()

Outlet_Location_Type  Outlet_Type
Tier 2                Supermarket Type1    1855
Tier 3                Grocery Store         555
dtype: int64

In [31]:
sales.loc[sales.Outlet_Size.isnull(), 'Outlet_Size']='Medium'

In [32]:
sales

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Item_ID_cat,Item_cat,Outlet_cat,Vintage
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,FD,perishable,Avg_performers,14
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,DR,non_perishable,Avg_performers,4
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,FD,perishable,Avg_performers,14
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,Medium,Tier 3,Grocery Store,732.3800,FD,perishable,Low_performers,15
4,NCD19,8.930,Non Edible,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,NC,non_perishable,High_performers,26
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834,FD,non_perishable,High_performers,26
8519,FDS36,8.380,Regular,0.046982,Baking Goods,108.1570,OUT045,2002,Medium,Tier 2,Supermarket Type1,549.2850,FD,non_perishable,Avg_performers,11
8520,NCJ29,10.600,Non Edible,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136,NC,non_perishable,Avg_performers,9
8521,FDN46,7.210,Regular,0.145221,Snack Foods,103.1332,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976,FD,non_perishable,Avg_performers,4
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700,DR,non_perishable,Avg_performers,16

# Scaling & Transformation

In [33]:
sales.columns

Index(['Item_Identifier', 'Item_Weight', 'Item_Fat_Content', 'Item_Visibility',
       'Item_Type', 'Item_MRP', 'Outlet_Identifier',
       'Outlet_Establishment_Year', 'Outlet_Size', 'Outlet_Location_Type',
       'Outlet_Type', 'Item_Outlet_Sales', 'Item_ID_cat', 'Item_cat',
       'Outlet_cat', 'Vintage'],
      dtype='object')

In [34]:
finaldata=sales.drop(['Item_Identifier','Item_Type', 'Outlet_Identifier',
       'Outlet_Establishment_Year'],axis=1)

In [35]:
finaldata

,Item_Weight,Item_Fat_Content,Item_Visibility,Item_MRP,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Item_ID_cat,Item_cat,Outlet_cat,Vintage
0,9.300,Low Fat,0.016047,249.8092,Medium,Tier 1,Supermarket Type1,3735.1380,FD,perishable,Avg_performers,14
1,5.920,Regular,0.019278,48.2692,Medium,Tier 3,Supermarket Type2,443.4228,DR,non_perishable,Avg_performers,4
2,17.500,Low Fat,0.016760,141.6180,Medium,Tier 1,Supermarket Type1,2097.2700,FD,perishable,Avg_performers,14
3,19.200,Regular,0.000000,182.0950,Medium,Tier 3,Grocery Store,732.3800,FD,perishable,Low_performers,15
4,8.930,Non Edible,0.000000,53.8614,High,Tier 3,Supermarket Type1,994.7052,NC,non_perishable,High_performers,26
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,6.865,Low Fat,0.056783,214.5218,High,Tier 3,Supermarket Type1,2778.3834,FD,non_perishable,High_performers,26
8519,8.380,Regular,0.046982,108.1570,Medium,Tier 2,Supermarket Type1,549.2850,FD,non_perishable,Avg_performers,11
8520,10.600,Non Edible,0.035186,85.1224,Small,Tier 2,Supermarket Type1,1193.1136,NC,non_perishable,Avg_performers,9
8521,7.210,Regular,0.145221,103.1332,Medium,Tier 3,Supermarket Type2,1845.5976,FD,non_perishable,Avg_performers,4
8522,14.800,Low Fat,0.044878,75.4670,Small,Tier 1,Supermarket Type1,765.6700,DR,non_perishable,Avg_performers,16

In [36]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
finaldata['scaled_sales']=sc.fit_transform(pd.DataFrame(finaldata.Item_Outlet_Sales))

In [37]:
sc=StandardScaler()
finaldata['scaled_mrp']=sc.fit_transform(pd.DataFrame(finaldata.Item_MRP))

In [38]:
sc=StandardScaler()
finaldata['scaled_weight']=sc.fit_transform(pd.DataFrame(finaldata.Item_Weight))

In [39]:
sc=StandardScaler()
finaldata['scaled_visibility']=sc.fit_transform(pd.DataFrame(finaldata.Item_Visibility))

In [40]:
sc=StandardScaler()
finaldata['scaled_vintage']=sc.fit_transform(pd.DataFrame(finaldata.Vintage))

In [41]:
newdata=finaldata.drop(['Item_Weight','Item_MRP','Item_Outlet_Sales','Vintage','Item_Visibility'],axis=1)

In [42]:
newdata['Outlet_Size']=newdata.Outlet_Size.map({'Small':1,'Medium':2,'High':3})

In [43]:
dummydata=pd.get_dummies(newdata, drop_first=True)

In [44]:
dummydata

,Outlet_Size,scaled_sales,scaled_mrp,scaled_weight,scaled_visibility,scaled_vintage,Item_Fat_Content_Non Edible,Item_Fat_Content_Regular,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3,Item_ID_cat_FD,Item_ID_cat_NC,Item_cat_perishable,Outlet_cat_High_performers,Outlet_cat_Low_performers
0,2,0.910601,1.747454,-0.769777,-0.970732,-0.139541,0,0,0,0,1,0,0,1,0,1,0,0
1,2,-1.018440,-1.489023,-1.497482,-0.908111,-1.334103,0,1,0,1,0,1,0,0,0,0,0,0
2,2,-0.049238,0.010040,0.995659,-0.956917,-0.139541,0,0,0,0,1,0,0,1,0,1,0,0
3,2,-0.849103,0.660050,1.361665,-1.281758,-0.020085,0,1,0,1,0,0,0,1,0,1,0,1
4,3,-0.695373,-1.399220,-0.849437,-1.281758,1.293934,1,0,0,1,1,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,3,0.349915,1.180783,-1.294026,-0.181193,1.293934,0,0,0,1,1,0,0,1,0,0,1,0
8519,2,-0.956402,-0.527301,-0.967851,-0.371154,-0.497909,0,1,1,0,1,0,0,1,0,0,0,0
8520,1,-0.579100,-0.897208,-0.489891,-0.599784,-0.736822,1,0,1,0,1,0,0,0,1,0,0,0
8521,2,-0.196725,-0.607977,-1.219748,1.532880,-1.334103,0,1,0,1,0,1,0,1,0,0,0,0
8522,1,-0.829594,-1.052261,0.414357,-0.411936,0.099372,0,0,0,0,1,0,0,0,0,0,0,0

In [45]:
newdata.describe(include='object')

,Item_Fat_Content,Outlet_Location_Type,Outlet_Type,Item_ID_cat,Item_cat,Outlet_cat
count,8523,8523,8523,8523,8523,8523
unique,3,3,4,3,2,3
top,Low Fat,Tier 3,Supermarket Type1,FD,non_perishable,Avg_performers
freq,3918,3350,5577,6125,5611,5573

# Multi collinearity

In [62]:
df_target=dummydata.scaled_sales

In [46]:
feature_df=dummydata.drop(['scaled_sales'],axis=1)
feature_df.head()

,Outlet_Size,scaled_mrp,scaled_weight,scaled_visibility,scaled_vintage,Item_Fat_Content_Non Edible,Item_Fat_Content_Regular,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3,Item_ID_cat_FD,Item_ID_cat_NC,Item_cat_perishable,Outlet_cat_High_performers,Outlet_cat_Low_performers
0,2,1.747454,-0.769777,-0.970732,-0.139541,0,0,0,0,1,0,0,1,0,1,0,0
1,2,-1.489023,-1.497482,-0.908111,-1.334103,0,1,0,1,0,1,0,0,0,0,0,0
2,2,0.010040,0.995659,-0.956917,-0.139541,0,0,0,0,1,0,0,1,0,1,0,0
3,2,0.660050,1.361665,-1.281758,-0.020085,0,1,0,1,0,0,0,1,0,1,0,1
4,3,-1.399220,-0.849437,-1.281758,1.293934,1,0,0,1,1,0,0,0,1,0,1,0

In [47]:
df_numeric=feature_df.loc[:,['Outlet_Size','scaled_mrp','scaled_weight','scaled_visibility','scaled_vintage']]

In [48]:
df_numeric.corr()

,Outlet_Size,scaled_mrp,scaled_weight,scaled_visibility,scaled_vintage
Outlet_Size,1.000000,-0.006059,0.004330,-0.069309,0.193389
scaled_mrp,-0.006059,1.000000,0.025967,-0.001315,-0.005020
scaled_weight,0.004330,0.025967,1.000000,-0.009215,0.013417
scaled_visibility,-0.069309,-0.001315,-0.009215,1.000000,0.074834
scaled_vintage,0.193389,-0.005020,0.013417,0.074834,1.000000

In [49]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [54]:
variance_inflation_factor(df_numeric.values,4)

1.0097537393663836

# Build the model

In [56]:
from statsmodels.formula.api import ols
import statsmodels.api as sm

In [59]:
# Add constant
x=sm.add_constant(feature_df)
x.head()

,const,Outlet_Size,scaled_mrp,scaled_weight,scaled_visibility,scaled_vintage,Item_Fat_Content_Non Edible,Item_Fat_Content_Regular,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3,Item_ID_cat_FD,Item_ID_cat_NC,Item_cat_perishable,Outlet_cat_High_performers,Outlet_cat_Low_performers
0,1.0,2,1.747454,-0.769777,-0.970732,-0.139541,0,0,0,0,1,0,0,1,0,1,0,0
1,1.0,2,-1.489023,-1.497482,-0.908111,-1.334103,0,1,0,1,0,1,0,0,0,0,0,0
2,1.0,2,0.010040,0.995659,-0.956917,-0.139541,0,0,0,0,1,0,0,1,0,1,0,0
3,1.0,2,0.660050,1.361665,-1.281758,-0.020085,0,1,0,1,0,0,0,1,0,1,0,1
4,1.0,3,-1.399220,-0.849437,-1.281758,1.293934,1,0,0,1,1,0,0,0,1,0,1,0

# Train the model

In [65]:
model=sm.OLS(df_target,x).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           scaled_sales   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.562
Method:                 Least Squares   F-statistic:                     731.3
Date:                Tue, 26 Jul 2022   Prob (F-statistic):               0.00
Time:                        16:34:20   Log-Likelihood:                -8563.6
No. Observations:                8523   AIC:                         1.716e+04
Df Residuals:                    8507   BIC:                         1.727e+04
Df Model:                          15
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                             0.0627      0.038      1.631      0.103      -0.013       0.138
Outlet_Size                      -0.0448      0.021     -2.111      0.035      -0.086      -0.003
scaled_mrp                        0.5676      0.007     79.023      0.000       0.554       0.582
scaled_weight                 -1.644e-05      0.007     -0.002      0.998      -0.014       0.014
scaled_visibility                -0.0092      0.008     -1.230      0.219      -0.024       0.005
scaled_vintage                   -0.1964      0.050     -3.916      0.000      -0.295      -0.098
Item_Fat_Content_Non Edible      -0.0029      0.014     -0.201      0.841      -0.031       0.025
Item_Fat_Content_Regular          0.0240      0.017      1.444      0.149      -0.009       0.056
Outlet_Location_Type_Tier 2      -0.1343      0.042     -3.204      0.001      -0.216      -0.052
Outlet_Location_Type_Tier 3      -0.2709      0.084     -3.221      0.001      -0.436      -0.106
Outlet_Type_Supermarket Type1     0.0591      0.028      2.123      0.034       0.005       0.114
Outlet_Type_Supermarket Type2    -0.0964      0.036     -2.702      0.007      -0.166      -0.026
Outlet_Type_Supermarket Type3     0.8931      0.032     27.670      0.000       0.830       0.956
Item_ID_cat_FD                    0.0075      0.026      0.286      0.775      -0.044       0.059
Item_ID_cat_NC                   -0.0029      0.014     -0.201      0.841      -0.031       0.025
Item_cat_perishable               0.0094      0.016      0.570      0.568      -0.023       0.042
Outlet_cat_High_performers        0.5857      0.155      3.773      0.000       0.281       0.890
Outlet_cat_Low_performers        -0.7931      0.063    -12.644      0.000      -0.916      -0.670
==============================================================================
Omnibus:                      958.043   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2284.439
Skew:                           0.666   Prob(JB):                         0.00
Kurtosis:                       5.159   Cond. No.                     2.45e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 8.87e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [66]:
model.pvalues[model.pvalues>0.05].index

Index(['const', 'scaled_weight', 'scaled_visibility',
       'Item_Fat_Content_Non Edible', 'Item_Fat_Content_Regular',
       'Item_ID_cat_FD', 'Item_ID_cat_NC', 'Item_cat_perishable'],
      dtype='object')

In [67]:
feature_df_v2=feature_df.drop(['scaled_weight', 'scaled_visibility',
       'Item_Fat_Content_Non Edible', 'Item_Fat_Content_Regular',
       'Item_ID_cat_FD', 'Item_ID_cat_NC', 'Item_cat_perishable'],axis=1)

# Build another model

In [68]:
x=sm.add_constant(feature_df_v2)
model_v2=sm.OLS(df_target,x).fit()
model_v2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           scaled_sales   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.562
Method:                 Least Squares   F-statistic:                     1218.
Date:                Tue, 26 Jul 2022   Prob (F-statistic):               0.00
Time:                        16:45:53   Log-Likelihood:                -8566.8
No. Observations:                8523   AIC:                         1.715e+04
Df Residuals:                    8513   BIC:                         1.722e+04
Df Model:                           9
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                             0.0744      0.034      2.201      0.028       0.008       0.141
Outlet_Size                      -0.0446      0.021     -2.103      0.036      -0.086      -0.003
scaled_mrp                        0.5679      0.007     79.249      0.000       0.554       0.582
scaled_vintage                   -0.1966      0.050     -3.921      0.000      -0.295      -0.098
Outlet_Location_Type_Tier 2      -0.1348      0.042     -3.216      0.001      -0.217      -0.053
Outlet_Location_Type_Tier 3      -0.2703      0.084     -3.215      0.001      -0.435      -0.106
Outlet_Type_Supermarket Type1     0.0641      0.027      2.338      0.019       0.010       0.118
Outlet_Type_Supermarket Type2    -0.0923      0.035     -2.612      0.009      -0.162      -0.023
Outlet_Type_Supermarket Type3     0.8988      0.032     28.181      0.000       0.836       0.961
Outlet_cat_High_performers        0.5851      0.155      3.770      0.000       0.281       0.889
Outlet_cat_Low_performers        -0.7962      0.062    -12.778      0.000      -0.918      -0.674
==============================================================================
Omnibus:                      960.799   Durbin-Watson:                   2.002
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2294.186
Skew:                           0.667   Prob(JB):                         0.00
Kurtosis:                       5.164   Cond. No.                     2.23e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.36e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""

In [69]:
x_v3=feature_df_v2.copy()

In [72]:
x_v3['Nf1']=x_v3['Outlet_Size']*x_v3['scaled_vintage']

In [73]:
x=sm.add_constant(x_v3)
model_v3=sm.OLS(df_target,x).fit()
model_v3.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           scaled_sales   R-squared:                       0.563
Model:                            OLS   Adj. R-squared:                  0.563
Method:                 Least Squares   F-statistic:                     1098.
Date:                Tue, 26 Jul 2022   Prob (F-statistic):               0.00
Time:                        16:53:39   Log-Likelihood:                -8563.8
No. Observations:                8523   AIC:                         1.715e+04
Df Residuals:                    8512   BIC:                         1.723e+04
Df Model:                          10
Covariance Type:            nonrobust
=================================================================================================
                                    coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
const                             0.1319      0.041      3.200      0.001       0.051       0.213
Outlet_Size                       0.0050      0.029      0.170      0.865      -0.053       0.063
scaled_mrp                        0.5679      0.007     79.260      0.000       0.554       0.582
scaled_vintage                   -0.4112      0.101     -4.055      0.000      -0.610      -0.212
Outlet_Location_Type_Tier 2      -0.1579      0.043     -3.675      0.000      -0.242      -0.074
Outlet_Location_Type_Tier 3      -0.4625      0.115     -4.011      0.000      -0.689      -0.236
Outlet_Type_Supermarket Type1    -0.0612      0.058     -1.050      0.294      -0.176       0.053
Outlet_Type_Supermarket Type2    -0.0198      0.046     -0.428      0.668      -0.110       0.071
Outlet_Type_Supermarket Type3     0.9732      0.044     22.037      0.000       0.887       1.060
Outlet_cat_High_performers        0.5036      0.159      3.172      0.002       0.192       0.815
Outlet_cat_Low_performers        -0.7603      0.064    -11.875      0.000      -0.886      -0.635
Nf1                               0.1212      0.050      2.434      0.015       0.024       0.219
==============================================================================
Omnibus:                      965.229   Durbin-Watson:                   2.003
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2307.927
Skew:                           0.669   Prob(JB):                         0.00
Kurtosis:                       5.170   Cond. No.                     2.38e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 9.23e-29. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.
"""